feat:[LAR-32] Add article list with action  in cpanel
laravelcm/laravel.cm pull request #160
Opened 2024-10-16 15:53 UTC by cybersoldattech

2024-10-16 16:03 UTC, mckenziearts requested changes

2024-10-16 16:03 UTC, mckenziearts commented on app/Filament/Resources/ArticleResource.php
> +                ->label('Status')
Pour cette section tu peux bien omettre le label ca sera automatiquement Status

2024-10-16 16:03 UTC, mckenziearts commented on app/Filament/Resources/ArticleResource/Pages/ListArticles.php
> +    protected function getHeaderActions(): array
Si c'est pas utilisé tu peux supprimer cette fonction

2024-10-16 16:03 UTC, mckenziearts commented on tests/Feature/Filament/ArticleTest.php
> +            ->toBe(null);
Tu peux rajouter le `and()` ici en lieu et place de faire 2 expect

2024-10-16 16:03 UTC, mckenziearts commented on tests/Feature/Filament/ArticleTest.php
> +    // it('admin user can deleted article', function () {
Si c'est pas utilisé faut le supprimer. Il ne faut pas garder un code qu'on utilise pas

2024-10-16 16:10 UTC, cybersoldattech commented on app/Filament/Actions/ApprovedAction.php
Je voulais que les autres actions suivent la meme logique comme DeleteAction et qu'au niveau du actionGroup que nous retrouvions uniquement les lignes des classe.

2024-10-16 16:10 UTC, cybersoldattech commented on app/Filament/Actions/DeclinedAction.php
> +    use CanCustomizeProcess;
OK

2024-10-16 16:10 UTC, cybersoldattech commented on app/Filament/Actions/ApprovedAction.php
> +    use CanCustomizeProcess;
ok

2024-10-16 16:12 UTC, cybersoldattech commented on app/Filament/Clusters/Articles.php
La dernière fois, je pense que tu nous as fait comprendre que nous devrions partir sur des clusters.

2024-10-16 16:47 UTC, mckenziearts commented
Tes commits doivent être compréhensible. J'ose review comment ne dit pas ce que Tu as fais.

2024-10-16 16:54 UTC, mckenziearts commented on app/Filament/Actions/ApprovedAction.php
Tu crée une classe pour une seule partie ou tu vas utiliser ça. Il faut faire ce qui est simple. Tu n'as pas besoin de reproduire une classe comme ce que tu as vu. Encore il va falloir répliquer cette action dans un bulk tu vas pas pouvoir gérer à convenable. Il faut toujours aller au plus faire. Je te le redis régulièrement faut faire simple.

2024-10-16 16:55 UTC, mckenziearts commented on app/Filament/Clusters/Articles.php
J'ai précisé ça sur le projet de IUG pas sur Laravel Cameroun

2024-10-16 16:56 UTC, mckenziearts requested changes
Il faut supprimer les classes que tu as crée la pour les actions et mettre ça dans le fichier de la resource

2024-10-16 21:34 UTC, mckenziearts requested changes

2024-10-16 21:34 UTC, mckenziearts commented on app/Filament/Resources/ArticleResource.php
> +                        ->action(fn (Collection $records) => $records->each->update(['approved_at' => now(), 'declined_at' => null]))
Y'a des conditions ici. Si on a déjà approuvé un article il faut masqué l'action pour approuver. Et quand on a décliné un article tu dois masqué l'action pour décliner.

**En gros**

- On peut approuver uniquement les articles soumis
- On ne peut pas approuver des articles qui ne sont pas soumis
- On peut peut décliner uniquement des articles qui ont été soumis
- On ne peut plus décliner un article qui est déjà approuvé

Chaque action tu dois afficher ou masque l'action qui correspond

2024-10-21 07:15 UTC, mckenziearts commented on tests/Feature/Filament/ArticleTest.php
> +    });
Même commentaire que le précédent

2024-10-21 08:23 UTC, mckenziearts approved these changes

2024-10-21 08:45 UTC, merged