Fix post views bugs
laravelcm/laravel.cm pull request #167
Opened 2024-10-26 15:59 UTC by jiordiviera

Correction de l'incrémentation des vues d'un post à l'actualisation de la page, et aussi ajout d'une image de secours lorsque l'image est inexistant. et aussi résolution du problème qui subvenait après avoir commenté une discussion .

2024-10-29 11:20 UTC, jiordiviera commented
@mckenziearts J'ai refait le PR, J'ai aussi remarqué lorsque je voulais faire un don que cela marque une erreur 500.

2024-10-30 07:31 UTC, mckenziearts requested changes

2024-10-30 07:31 UTC, mckenziearts commented on app/Http/Controllers/ArticlesController.php
> +        views($article)->cooldown(now()->addHours(2))->record();
Que résoud cette action et quel comportement tu reçois et comment devrait-il normalement se comporter

2024-10-30 07:31 UTC, mckenziearts commented on app/Http/Livewire/Discussions/AddComment.php
> +        $this->reset('body');
C'est la même chose. Le reset réinitialise toutes les variables du formulaire

2024-10-30 07:31 UTC, mckenziearts commented on app/helpers.php
> +if(! function_exists('getAvatar')) {
Pas nécessaire

2024-10-30 07:31 UTC, mckenziearts commented on resources/views/articles/show.blade.php
> +                                    <img class="h-10 w-10 object-cover shadow-lg rounded-md" src="{{ $next->getFirstMediaUrl('media') ?? asset('images/socialcard.png') }}" alt="{{ $next->slug }}" one
Le onerror c'est quoi son utilité vu que il y'a déjà une condition? C'est la condition qu'il faut revoir

2024-10-30 09:42 UTC, jiordiviera commented on app/Http/Controllers/ArticlesController.php
> +        views($article)->cooldown(now()->addHours(2))->record();
`views($article)->record();`
la première ligne comptabilise chaque vue sans restriction, tandis que `views($article)->cooldown(now()->addHours(2))->record();` impose une attente de 2 heures entre les enregistrements de vues pour le même article.

2024-10-30 09:46 UTC, jiordiviera commented on resources/views/articles/show.blade.php
> +                                    <img class="h-10 w-10 object-cover shadow-lg rounded-md" src="{{ $next->getFirstMediaUrl('media') ?? asset('images/socialcard.png') }}" alt="{{ $next->slug }}" one
Le `onerror` gère les erreurs de chargement d'image et utilise une image alternative si le chargement échoue, ce qui améliore l'expérience utilisateur en fournissant une option de secours. car j'ai remarque sur la plateforme des images n'ayant pas chargé donc n'existant pas, et la place c'est le `title `de l'image qui s'affichait et cela détruisait l'ui

2024-10-30 09:48 UTC, jiordiviera commented on app/helpers.php
> +if(! function_exists('getAvatar')) {
Ici je voulais faire une illustration afin de simuler l'utilisation du `onerror`, ce n'était pas définitif.

2024-10-30 12:02 UTC, mckenziearts commented on app/Http/Controllers/ArticlesController.php
> +        views($article)->cooldown(now()->addHours(2))->record();
Si 50 personnes regardent l'article au bout de 10 minutes il n'enregistre pas les 50 records ? Ou tu dis qu'il va enregistrer les 50 records après 2h

2024-10-30 13:49 UTC, jiordiviera commented on app/Http/Controllers/ArticlesController.php
> +        views($article)->cooldown(now()->addHours(2))->record();
Non c'est pour dire que un utilisateur ne pourrait voir le post deux fois de suite, genre sa vue sera mis en cache de tel sorte que si il voit un poste, en actualisant le navigateur, on considérera que il a déjà vu le post , la le nombre de vue ne sera pas incrémenté cela pendant les deux prochaines heures. donc la vue de post par cette utilisateur sera gelée.

2024-10-31 04:07 UTC, mckenziearts requested changes
Une fois que tu auras effectué les retours je pourrai merge ta PR

2024-10-31 04:07 UTC, mckenziearts commented on app/helpers.php
> +if(! function_exists('getAvatar')) {
Faut supprimer cette fonction du coup on ne garde pas du coup qui n'est pas utile

2024-10-31 04:07 UTC, mckenziearts commented on resources/views/articles/show.blade.php
> +                                    <img class="h-10 w-10 object-cover shadow-lg rounded-md" src="{{ $next->getFirstMediaUrl('media') ?? asset('images/socialcard.png') }}" alt="{{ $next->slug }}" one
C'est la condition qu'il faut corriger dans ce cas parce que si un article n'a pas d'image il y'a un placeholder normalement

2024-11-01 04:52 UTC, mckenziearts requested changes

2024-11-01 04:52 UTC, mckenziearts commented on resources/views/livewire/articles/_form.blade.php
@jiordiviera ce que je dis souvent c'est que si un fichier n'entre pas dasn le scope de ta tache faudrait éviter de les modifier. Parce que tu modifies ce fichier pourtant ta feature n'a pas besoin de le faire.

2024-11-01 04:52 UTC, mckenziearts commented on resources/views/components/forms/single-upload.blade.php
> +                <input @focus="focused = true" @blur="focused = false" class="sr-only" type="file" accept="image/jpg, image/jpeg, image/png" {{ $attributes }} />
Annule cette modification

2024-11-01 04:52 UTC, mckenziearts commented on resources/views/components/articles/overview.blade.php
> +                 alt="{{ $article->title }}" onerror="this.src='{{ asset('images/socialcard.png') }}'"
Annule cette modification

2024-11-01 04:52 UTC, mckenziearts commented on resources/views/components/articles/card.blade.php
> +            <img class="object-cover shadow-lg rounded-lg group-hover:opacity-75" src="{{ $article->getFirstMediaUrl('media') }}" alt="{{ $article->title }}" onerror="this.onerror=null;this.src='{{ a
Annule cette modification

2024-11-01 04:52 UTC, mckenziearts commented on resources/views/components/articles/card-with-author.blade.php
> +            <img class="w-full h-full object-cover shadow-lg rounded-lg group-hover:opacity-75" src="{{ $article->getFirstMediaUrl('media') }}" alt="{{ $article->title }}" onerror="this.src='{{ asset
Annule cette modification

2024-11-01 04:52 UTC, mckenziearts commented on resources/views/articles/show.blade.php
> +                                    <img class="h-10 w-10 object-cover shadow-lg rounded-md" src="{{ $previous->getFirstMediaUrl('media') ?? asset('images/socialcard.png') }}" alt="{{ $previous->slug
Annule cette modification

2024-11-01 04:52 UTC, mckenziearts commented on resources/views/articles/show.blade.php
> +                                    <img class="h-10 w-10 object-cover shadow-lg rounded-md" src="{{ $next->getFirstMediaUrl('media') ?? asset('images/socialcard.png') }}" alt="{{ $next->slug }}" one
Annule cette modification

2024-11-01 04:52 UTC, mckenziearts commented on resources/views/articles/show.blade.php
> +                                    <button onclick="Livewire.emit('openModal', 'modals.approved-article', {{ json_encode([$article->id]) }})" type="button" class="-ml-px relative inline-flex items-c
rétabli les classes que tu as retiré

2024-11-01 04:52 UTC, mckenziearts commented on resources/views/articles/show.blade.php
> +                                    <img class="h-8 w-8 object-cover shadow-lg rounded-md" src="{{ $previous->getFirstMediaUrl('media') }}" alt="{{ $previous->slug }}" onerror="this.onerror=null;this
Annule cette modification

2024-11-01 07:54 UTC, mckenziearts approved these changes

2024-11-01 07:57 UTC, merged