feat: [LAR-30] Add filament resource user in cpanel
laravelcm/laravel.cm pull request #201
Opened 2024-11-07 21:16 UTC by cybersoldattech

2024-11-07 21:55 UTC, mckenziearts requested changes

2024-11-07 21:55 UTC, mckenziearts commented on app/Filament/Resources/UserResource.php
> +                TextColumn::make(name: 'Points')
Pas utile comme information

2024-11-07 21:55 UTC, mckenziearts commented on package-lock.json
Le fichier si ne dois pas exister

2024-11-07 21:55 UTC, mckenziearts commented on app/Filament/Resources/UserResource.php
> +                $query->withoutRole(['admin', 'moderator']);
Cette query donne les bons résultats ?

2024-11-07 22:08 UTC, cybersoldattech commented on app/Filament/Resources/UserResource.php
> +                $query->withoutRole(['admin', 'moderator']);
Oui je vais pousser le test maintenant j'ai create des users j'ai assign des roles et j'ai fais le test sur le count du tableau et c'est ok

2024-11-07 22:09 UTC, cybersoldattech commented on app/Filament/Resources/UserResource.php
> +                TextColumn::make(name: 'Points')
Ok

2024-11-09 01:24 UTC, mckenziearts requested changes

2024-11-09 01:24 UTC, mckenziearts commented on tests/Feature/Filament/UserTest.php
> +
Faut supprimer cet espace

2024-11-09 01:24 UTC, mckenziearts commented on tests/Pest.php
Il y'a un trait `CreatesUser` ou tu peux rajouter cette function en suivant le pattern défini dans le fichier

2024-11-09 10:49 UTC, merged