fix: (LAR-21) resolve sharing article into twitter
laravelcm/laravel.cm pull request #208
Opened 2024-11-08 21:02 UTC by StevyMarlino

2024-11-08 21:42 UTC, mckenziearts requested changes

2024-11-08 21:42 UTC, mckenziearts commented on tests/Feature/Article/PostArticleToTwitterTest.php
> +beforeEach(fn () =>
Pourquoi j'ai l'impression qu'il y'a pas d'espace ici? Et pourquoi utilisé une arrow function ?

2024-11-08 21:42 UTC, mckenziearts commented on tests/Feature/Article/PostArticleToTwitterTest.php
> +            ['submitted_at' => now(),],
La virgule peut être enlevé quand tu n'as pas de valeur qui suit

2024-11-08 21:49 UTC, StevyMarlino commented on tests/Feature/Article/PostArticleToTwitterTest.php
> +            ['submitted_at' => now(),],
ok ..

2024-11-08 21:50 UTC, StevyMarlino commented on tests/Feature/Article/PostArticleToTwitterTest.php
> +beforeEach(fn () =>
haha, la syntaxe est plus petite et ça fait le taff

2024-11-09 01:22 UTC, mckenziearts approved these changes

2024-11-09 01:22 UTC, merged