feat: (LAR-86) add bannished sysem
laravelcm/laravel.cm pull request #218
Opened 2024-11-11 19:53 UTC by StevyMarlino

bannish user
unbannished user
bannished user can not login
send mail when ban or unban user

2024-11-12 20:20 UTC, StevyMarlino commented on app/Http/Middleware/CheckIfBanned.php
> +                'email' => __('Votre compte a été banni. Contactez l\'administrateur pour plus d\'informations.'),
d'accord

2024-11-12 20:56 UTC, mckenziearts requested changes

2024-11-12 20:56 UTC, mckenziearts commented on app/Filament/Resources/UserResource.php
> +                    ->label(__('global.ban.label.inscription'))
Pourauoi tu mets cela dans une clé ban pourtant ca n'a rien avoir ?

2024-11-12 20:56 UTC, mckenziearts commented on app/Filament/Resources/UserResource.php
> +                    ->label(__('global.ban.label.validate_email'))
tu peux pas mettre cela dans une clé ban il y'a pas de logique a cela

2024-11-12 20:56 UTC, mckenziearts commented on app/Filament/Resources/UserResource.php
> +                    ->label(__('global.ban.label.email_verified'))
Pareil

2024-11-12 20:56 UTC, mckenziearts commented on app/Filament/Resources/UserResource.php
> +                        ->modalHeading(__('global.ban.heading'))
Et ce n'est pas quelque chose de global. Tu devrais crée un fichier `user` ou `profile` dans le dossier de traduction

2024-11-12 20:56 UTC, mckenziearts commented on app/Filament/Resources/UserResource.php
> +                ->title(__('notifications.user.cannot.title'))
La traduction n'est pas comprehensible. et tu as beaucoup trop de clé user / cannot / title tu peux faire simple `notifications.user.ban_title`, `notifications.user.ban_message`

2024-11-12 20:56 UTC, mckenziearts commented on app/Filament/Resources/UserResource.php
> +            ->title(__('notifications.user.unbanned.title'))
`notifications.user.unbaned_title`, `notifications.user.unbaned_message`

2024-11-12 20:56 UTC, mckenziearts commented on app/Filament/Resources/UserResource/Pages/ListUsers.php
> +          __('global.ban.all') => Tab::make(__('global.ban.all')),
Tu ne peux pas traduire les clés d'un table. Ce sont les valeurs qui sont interessantes. Tes tabs doivent être `all`, `ban` et `unbanned`

2024-11-12 20:56 UTC, mckenziearts commented on app/Mail/UserBannedEMail.php
> +            subject: __('global.ban.ban_email_subject'),
la clé est trop longue. Met dans un fichier `user` ou `profile` et tu regroupes toutes les traductions dans des clés ban et unbanned

2024-11-12 20:56 UTC, mckenziearts commented on app/Mail/UserUnBannedEMail.php
> +            subject: __('global.ban.unban_email_subject'),
Même commentaire que le precedent

2024-11-12 20:56 UTC, mckenziearts commented on app/Events/UserUnbannedEvent.php
> +    public function broadcastOn(): array
Si les channels ne sont pas utilisés faut les supprimer

2024-11-12 20:56 UTC, mckenziearts commented on app/Events/UserBannedEvent.php
> +    public function broadcastOn(): array
Si les channels ne sont pas utilisés faut les supprimer

2024-11-12 20:56 UTC, mckenziearts commented on app/Listeners/SendBanNotificationListener.php
> +    public function __construct()
Ce fichier montre que tu n'as pas run composer lint

2024-11-12 20:56 UTC, mckenziearts commented on database/migrations/2024_11_10_032051_add_ban_field_to_users_table.php
> +            $table->dropColumn('banned_at');
Tu peux passer un tableau avec les 2 colonnes directement

2024-11-12 20:56 UTC, mckenziearts commented on resources/views/emails/send-user-banned-message.blade.php
Tu peux apper ta vue `send-banned-message`. C'est forcement a un user qu'on envoie un message pour bannir preciser le nom dans le fichier c'est un peu répétitif

2024-11-12 20:56 UTC, mckenziearts commented on resources/views/emails/send-user-unbanned-message.blade.php
Même remarque pour le nom du fichier

2024-11-12 20:56 UTC, mckenziearts commented on tests/Feature/Filament/UserResourceTest.php
> +        UserResource::BanUserAction($user, 'Violation des règles de la communauté');
Tres mauvais pattern. Les actions doivent etre dans un dossier `Actions` et ne sont pas des appels static. On ne peut pas tester cette action a part. C'est rattaché a ta ressource. Si demain on veut utiliser cette action via ne api on va utiliser la resource dans un context qui n'est pas le sien

2024-11-12 20:56 UTC, mckenziearts commented on tests/Feature/Filament/UserResourceTest.php
> +        UserResource::UnbanUserAction($user);
Même commentaire que le precedent

2024-11-13 08:38 UTC, mckenziearts commented on tests/Feature/Filament/UserResourceTest.php
> +    })->skip();
Pourquoi tu le skip?

2024-11-13 08:44 UTC, mckenziearts commented on tests/Feature/Filament/UserResourceTest.php
> +        // $this->get('/cp')->assertSuccessful();
Tu dois juste tester que ton utilisateur accède à la ressource. Tu n'as pas besoin de tester cette url parce que c'est pas sur cette url que se trouve ta resource

2024-11-13 08:44 UTC, mckenziearts commented on tests/Feature/Filament/UserResourceTest.php
> +        // $this->get('/cp')->assertSuccessful();
Meme remarque

2024-11-13 08:45 UTC, mckenziearts commented on tests/Feature/Filament/UserResourceTest.php
>          $user = User::factory()->create([
Creer un helper `banned()` et `unbanned()` au niveau de la factory pour pouvoir faire quelque chose comme `User::factory()->banned()->create()`

2024-11-14 01:36 UTC, StevyMarlino commented on tests/Feature/Filament/UserResourceTest.php
> +    })->skip();
La route n'est pas aussi trouvé quand c'est exécuté sur git

2024-11-14 06:14 UTC, mckenziearts requested changes

2024-11-14 06:14 UTC, mckenziearts commented on app/Http/Middleware/CheckIfBanned.php
> +        if (Auth::check() && Auth::user()->banned_at) {
Créer un exemple dans le model User qui te dira si l'utilisateur est banni ou pas du style

```php
Auth::user()->isBanned()
```

Ca permet demain de pouvoir personnaliser cette fonction si on veut prendre en compte autre chose en plus de la date de ban. Et tu fais aussi une fonction pour savoir s'il n'est pas banni. Ça rend le code facile a comprendre et à lire

2024-11-14 06:14 UTC, mckenziearts commented on app/Jobs/SendBanEmailJob.php
> +        Mail::to($this->user->email)->send(new UserBannedEMail($this->user));
Faut envoyer une **Notification** pas un **Mail**

2024-11-14 06:14 UTC, mckenziearts commented on app/Jobs/SendUnbanEmailJob.php
> +        Mail::to($this->user->email)->send(new UserUnBannedEMail($this->user));
Envoyer une **Notification** par un **Mail**. Parce qu'on notifie l'utilisateur qu'on a banni son compte.

2024-11-14 06:14 UTC, mckenziearts commented on app/Listeners/SendBanNotificationListener.php
> +    public function __construct()
Supprimer ce constructeur s'il n'est pas utilisé

2024-11-14 06:14 UTC, mckenziearts commented on app/Listeners/SendUnbanNotificationListener.php
> +    public function __construct()
Supprimer ce constructeur

2024-11-14 06:14 UTC, mckenziearts commented on app/Policies/UserPolicy.php
> +        return $user->hasRole('admin');
Dans le model User y'a des helpers `$user->isAdmin()` et `$user->isModerator()` que tu dois utiliser ici. C'est la même chose que sur les autres classes Policies

2024-11-14 06:14 UTC, mckenziearts commented on app/Providers/AppServiceProvider.php
> +        Gate::policy(User::class, UserPolicy::class);
C'est automatiquement détecter par Laravel donc tu n'es pas obligé de rajouter cette ligne

2024-11-14 06:14 UTC, mckenziearts commented on database/migrations/2024_11_10_032051_add_ban_field_to_users_table.php
> +            $table->timestamp('banned_at')->nullable();
Le champ `banned_reason` avant le `bannet_at` et tu dois mettre les champs la juste avant le `created_at`. Donc tu regardes le champs qui vient juste avant created_at et tu rajoutes les colonnes juste après ce champ

2024-11-14 06:14 UTC, mckenziearts commented on tests/Feature/Filament/UserResourceTest.php
> +    })->skip();
Pousse ça comme cela je vais regarder ça. On ne skip aucun test

2024-11-14 11:06 UTC, StevyMarlino commented on tests/Feature/Filament/UserResourceTest.php
> +    })->skip();
d'accord

2024-11-14 12:39 UTC, mckenziearts requested changes

2024-11-14 12:39 UTC, mckenziearts commented on database/migrations/2024_11_10_032051_add_ban_field_to_users_table.php
> +            $table->string('banned_reason')->after('reputation')->nullable();
```php
$table->after('reputation', function (Blueprint $table): void {
    $table->string('banned_reason')->nullable();
    $table->timestamp('banned_at')->nullable();
})
```

2024-11-14 19:31 UTC, mckenziearts approved these changes

2024-11-14 20:08 UTC, merged