fea: (LAR-87) Mise en place des test pour la signalisation d'un contenu
laravelcm/laravel.cm pull request #222
Opened 2024-11-12 22:11 UTC by Stephen2304

2024-11-20 23:03 UTC, StevyMarlino requested changes

2024-11-20 23:03 UTC, StevyMarlino commented on app/Contracts/SpamReportableContract.php
> +}
un trait aurait peut être convenu vu ce que tu as fait dans tes models

2024-11-21 05:25 UTC, mckenziearts commented on app/Actions/ReportSpamAction.php
> +    public function execute(User $user, SpamReportableContract $model, ?string $content = null): void
Non il y'a la différence le `?` signifie quand la variable peut être optionnel pas que c'est null, l'initialisation c'est pour dire que c'est null. A ne pas confondre

2024-11-21 05:26 UTC, mckenziearts commented on app/Models/Discussion.php
> +    }
l'interface c'est pour créer un contrat avec les models. Tu as regardé la définition de la fonction `execuute` dans la classe `ReportSpamAction` ?

2024-11-21 05:27 UTC, mckenziearts commented on app/Notifications/ReportedSpamToTelegram.php
> +            ->button('Voir les spams', route('filament.admin.pages.dashboard'));
Pas besoin de trad ici c'est pour nous envoyez les notifications direct sur Telegram

2024-11-21 05:29 UTC, mckenziearts commented on tests/Feature/Livewire/ReportSpamTest.php
> +            ->toBe('thread');
Dans une relation Polymorphic le champ `**_type` est toujours une chaîne de caractère pas un object c'est `reportable` qui doit être une instance

2024-11-21 05:48 UTC, mckenziearts commented on tests/Feature/Livewire/ReportSpamTest.php
> +            ->toBeTrue();
Les tests que tu corriges ne donnent pas le but du test. Le but est d'êmpécher qu'un spam soit report 2 fois par la même utilisateur pour le même thread. D'ou on vérifie déjà le nombre de spam pour ce report et on check si dans les spams il y'en a qui appartiennent à l'utilisateur qui report encore ce spam

Un Thread a plusieurs spam donc `$thread->spamReports()` ne peut pas être une instance de `SpamReport` mais sera une instance de `Illuminate\Support\Collection` (repere toi à la relation)

2024-11-21 09:37 UTC, StevyMarlino approved these changes

2024-11-21 09:37 UTC, StevyMarlino commented on app/Actions/ReportSpamAction.php
> +    public function execute(User $user, SpamReportableContract $model, ?string $content = null): void
ahnn okay je pensais que lorsque c 'est optionnelle, elle passe directement a null

2024-11-21 09:37 UTC, StevyMarlino commented on app/Models/Discussion.php
> +    }
oui oui j'avais vu. 
mais mon soucis est que c étais le même contrat partout sauf si la redéfinition devais changer.

2024-11-21 09:37 UTC, StevyMarlino commented on app/Notifications/ReportedSpamToTelegram.php
> +            ->button('Voir les spams', route('filament.admin.pages.dashboard'));
d'accord

2024-11-21 09:37 UTC, StevyMarlino commented on tests/Feature/Livewire/ReportSpamTest.php
> +            ->toBe('thread');
ah oui c'est vrai. je comprends mieux

2024-11-21 09:37 UTC, StevyMarlino commented on tests/Feature/Livewire/ReportSpamTest.php
> +            ->toBeTrue();
donc on peut faire un 
`toBeInstanceOf(Collection::class)` ?

2024-11-21 09:42 UTC, merged