feat:[LAR-129] Add Filament resource Thread in Admin
laravelcm/laravel.cm pull request #244
Opened 2024-12-10 11:31 UTC by cybersoldattech

2024-12-10 12:48 UTC, mckenziearts commented on app/Filament/Resources/ThreadResource.php
> +                    ->label('Résolut')
Le label si ne veut absolu pas dire ce que la colonne défini. C'est resolved by traduit par `résolu par`. Mais on a même pas de colonne pour savoir si le sujet est résolu avant de savoir par qui. Mais l'information importante est de savoir si c'est résolu. Après on peut cliquer poru afficher le sujet pour voir qui l'a résolu

2024-12-10 13:23 UTC, cybersoldattech commented on app/Filament/Resources/ThreadResource.php
> +    public static function getNavigationGroup(): ?string
Quand je supprime il me sort cette erreur 
**Type must be 'null|string' (as in base class '\Filament\Resources\Resource')** 
et quand je rajout le |null il refactor pour remettre le point d'interrogation

2024-12-10 13:24 UTC, cybersoldattech commented on app/Filament/Resources/ThreadResource.php
> +                    ->label('Résolut')
Oui mais je pense que  si la colonne **resolved_by** a une valeur cela veut dire que le sujet est resolut. et c'est pour cette raison que j'ai mis comme label **résolut** a la place de **résolu par** car dans la table il y'a pas un boolean qui permet de le savoir , je verifie juste si resolved_by est null ou pas pour savoir si le sujet est résolu ou pas

2024-12-10 15:41 UTC, mckenziearts requested changes

2024-12-10 15:41 UTC, mckenziearts commented on app/Filament/Resources/ThreadResource.php
> +                TextColumn::make('resolvedBy.name')
Remplace pour savoir plutot si c'est résolu ou pas. Parce que si c'est pas résolu on va avoir cette colonne qui sera toujours vide

2024-12-11 06:29 UTC, mckenziearts requested changes

2024-12-11 06:29 UTC, mckenziearts commented on app/Filament/Resources/ThreadResource.php
> +                    ->label(fn ($state) => $state)
Le label c'est juste **Résolu**. Si c'est l'unique moyen de savoir si un sujet est résolu ou pas. Et tu dois utilisé cette colonne comme une icône et tu fais comme le reste.

Et tu dois avoir un `formatStateUsing` à la place de `getStateUsing` et dans le format tu retournes un bool

```php
formatStateUsing(fn ($record): bool => (bool) $record->resolved_by)
```

Ça devrait te retourner true ou false en fonction si ça existe ou pas. En gros voilà l'idée

2024-12-11 06:29 UTC, mckenziearts commented on app/Filament/Resources/ThreadResource.php
> +                    ->color(fn ($record) => ($record?->resolved_by == null) ? 'warning' : 'success'),
Et tu vas profiter pour supprimer cette line

2024-12-11 18:46 UTC, cybersoldattech commented on app/Filament/Resources/ThreadResource.php
> +                    ->label(fn ($state) => $state)
Le **formatStateUsing** n'est pas prise en compte par IconColumn.

2024-12-13 10:30 UTC, mckenziearts approved these changes

2024-12-13 13:32 UTC, merged