feat:[lar-140] Remove point after deleted article ,thread and discussion
laravelcm/laravel.cm pull request #252
Opened 2024-12-17 17:56 UTC by cybersoldattech

2024-12-17 18:25 UTC, mckenziearts requested changes

2024-12-17 18:25 UTC, mckenziearts commented on app/Filament/Resources/ArticleResource.php
> +                    Tables\Actions\DeleteAction::make()
La PR est si l'utilisateur supprime son article pas l'admin. La feature la doit être cote front pas coté back

2024-12-17 18:25 UTC, mckenziearts commented on app/Filament/Resources/DiscussionResource.php
> +                    ->after(fn ($record) => undoPoint(new DiscussionDeleted($record))),
A faire cote front pas cote back

2024-12-17 18:25 UTC, mckenziearts commented on app/Filament/Resources/ThreadResource.php
> +                    Tables\Actions\DeleteAction::make()
Uniquement à faire cote front

2024-12-18 10:21 UTC, mckenziearts requested changes

2024-12-18 10:21 UTC, mckenziearts commented on app/Livewire/Pages/Discussions/SingleDiscussion.php
> +            ->after(fn ($record) => undoPoint(new DiscussionCreated($record)));
Comment tu peux undo le point ici pourtant le after s'effectue après que le model soit supprimé. Tu as ecris un test pour vérifier ?

2024-12-18 10:21 UTC, mckenziearts commented on app/Livewire/Pages/Forum/DetailThread.php
> +                undoPoint(new ThreadCreated($this->thread));
Tu supprimes le model et tu passe le model comment ? A la ligne 59 `$this->thread` peut etre null parce que tu l'as supprimé juste avant. Tu dois mettre ça dans une transaction et tu supprimes le point avant de supprimer le model pas l'inverse

2024-12-18 14:05 UTC, mckenziearts requested changes

2024-12-18 14:05 UTC, mckenziearts commented on app/Livewire/Pages/Forum/DetailThread.php
> +                DB::beginTransaction();
Dans une action quand on comment déjà à avoir beaucoup de logique

2024-12-18 14:05 UTC, mckenziearts commented on tests/Feature/Livewire/Pages/Discussion/SIngleDiscussionTest.php
Le nom de ton fichier doit être **SingleDiscussionTest** et non **SIngleDiscussionTes**

2024-12-18 14:36 UTC, cybersoldattech commented on app/Livewire/Pages/Forum/DetailThread.php
> +                DB::beginTransaction();
c'est la seule arternative que j'ai vue pour pourvoir add les transactions.

2024-12-18 15:45 UTC, mckenziearts approved these changes

2024-12-18 15:45 UTC, mckenziearts commented on app/Livewire/Pages/Forum/DetailThread.php
> +                DB::beginTransaction();
Je disais de creer un fichier Action et de faire cette logique labas et juste appeler l'action ici

2024-12-18 21:40 UTC, merged