feat: (LAR-138) update user dashboard
laravelcm/laravel.cm pull request #266
Opened 2024-12-24 13:10 UTC by StevyMarlino

2024-12-25 07:48 UTC, mckenziearts requested changes

2024-12-25 07:48 UTC, mckenziearts commented on app/Actions/Article/ArticleDeleteAction.php
> +        DB::beginTransaction();
Pourquoi une transaction sur une seule requete ? Et pourquoi une action pour ceci ?

2024-12-25 07:48 UTC, mckenziearts commented on lang/fr/pages/discussion.php
> +    'write_discussion' => 'Rédiger une discussion',
Je crois que cette clé on l'a supprimé ou on ne l'utilise pas

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/components/discussions/overview.blade.php
> +    <p class="mt-2 text-gray-500 dark:text-white line-clamp-2">
le dark de `gray-500` ce n'est pas white c'est `gray-400` ou la limite tu mets `gray-300` mais pas white

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/components/discussions/overview.blade.php
> +<div @if($displayClass) class="py-6" @endif >
Pourquoi cette condition? Surtout que tu peux utiliser les slots

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/components/forum/thread-channels.blade.php
> +                    @foreach ($channels as $channel)
C'est moi ou ce code n'est pas bien indenté ?

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/components/forum/thread-channels.blade.php
> +    @endif
Un espace après le endif

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/components/user/sidebar.blade.php
Ce composant est encore utilisé ?

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/components/icon/tags/aws.blade.php
Pourquoi avoir créé ce fichier sans rien à l'intérieur ? S'il n'est pas utilisé faut le supprimer

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/articles.blade.php
> +    use WithPagination, WithoutUrlPagination;
Les uses sont les uns après pas les autres. Tu peux pas commencer avec 2 traits côte à côte puis tu pars à la ligne pour les autres. Tous doivent être à la ligne

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/articles.blade.php
> +            ->color('warning')
La couleur est gray, par warning

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/articles.blade.php
> +                                        {{ $this->editAction()(['article' => $article->id]) }}
Tu lui passes l'id mais tu appelles la clé `article`, renomme soit en `id` soit en `articleId` pour garder une certaine cohérence pour la lecture

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/articles.blade.php
> +                                    {{ $this->deleteAction()(['article' => $article->id]) }}
Même retour que pour le commentaire précédent

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/articles.blade.php
> +                            <a href="{{ route('profile', $article->user->username) }}" class="shrink-0">
pour les liens il ya le composant `x-link` et pour la photo tu as le composant `x-user.avatar`

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/articles.blade.php
> +                                    <a href="{{ route('profile', $article->user->username) }}" class="hover:underline">
`x-link`

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/articles.blade.php
> +                                            <span>En attente d'approbation</span>
Manque de trad ici

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/articles.blade.php
> +                                            {{ __('Publié le :date', ['date' => $article->submitted_at->format('j M, Y')]) }}
La trad ?

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/articles.blade.php
> +                                                Rédigé
La trad

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/articles.blade.php
> +                                    <span>{{ $article->readTime() }} min de lecture</span>
Tu as une trad pour ceci quand tu regardes la page de détail d'un article

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/discussions.blade.php
> +    use WithPagination, WithoutUrlPagination;
Même commentaire que pour le fichier précédent

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/discussions.blade.php
> +        return <<<'HTML'
Il y'a un dossier skeletons dans les composants, créé un skeleton pour ceci, colle ton code dans le fichier et retourne ce fichier dans ton placeholder

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/discussions.blade.php
> +            ->color('warning')
couleur gray ou info

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/threads.blade.php
> +    use WithPagination, WithoutUrlPagination;
Même retour pour les traits

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/threads.blade.php
> +    public function placeholder(): string
Même retour que le précédent pour le placeholder

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/livewire/components/account/threads.blade.php
> +            ->color('warning')
couleur gray ou info pour les editions

2024-12-25 07:48 UTC, mckenziearts commented on resources/views/user/threads.blade.php
>                  <x-user.page-heading title="Vos sujets" url="#" :button="__('Nouveau sujet')" />
la trad ?

2024-12-25 09:03 UTC, mckenziearts requested changes

2024-12-25 09:03 UTC, mckenziearts commented on resources/views/livewire/components/account/discussions.blade.php
> +        return view('components.skeletons.account');
Tu es sur un composant `discussions` et tu appelles le skeleton `account`

2024-12-25 09:29 UTC, cybersoldattech commented on resources/views/livewire/components/account/discussions.blade.php
> +        return view('components.skeletons.account');
j'ai d'abord créé un skeleton discussion et un autre thread, mais après je me suis rendu compte que les deux ont le même contenu et comment nous sommes dans la section account de setting. J'ai renommé cela en account pour les use aux deux endroits

2024-12-25 11:14 UTC, StevyMarlino commented on resources/views/components/icon/tags/aws.blade.php
ce fichier est checker lorsque quelqu un choisis le tag aws. d ou sa présence.

2024-12-25 23:35 UTC, cybersoldattech approved these changes

2024-12-26 10:25 UTC, mckenziearts approved these changes

2024-12-26 10:26 UTC, merged